//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class afarmaciaEntities : DbContext
    {
        public afarmaciaEntities()
            : base("name=afarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assinante> Assinante { get; set; }
        public virtual DbSet<Avenida> Avenida { get; set; }
        public virtual DbSet<Carrinho> Carrinho { get; set; }
        public virtual DbSet<Categoria_usuario> Categoria_usuario { get; set; }
        public virtual DbSet<Classificacao_farmacia> Classificacao_farmacia { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Configuracao> Configuracao { get; set; }
        public virtual DbSet<Dependente> Dependente { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Doencas> Doencas { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Fabricante> Fabricante { get; set; }
        public virtual DbSet<Farmacia> Farmacia { get; set; }
        public virtual DbSet<Grupo_medicamento> Grupo_medicamento { get; set; }
        public virtual DbSet<Log_erro> Log_erro { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Medicamento_farmacia> Medicamento_farmacia { get; set; }
        public virtual DbSet<Ordem> Ordem { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Posicao_padrao> Posicao_padrao { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Receita> Receita { get; set; }
        public virtual DbSet<Regiao> Regiao { get; set; }
        public virtual DbSet<Relatorio> Relatorio { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Seguradora> Seguradora { get; set; }
        public virtual DbSet<Seguro_categoria> Seguro_categoria { get; set; }
        public virtual DbSet<Seguro_depedente> Seguro_depedente { get; set; }
        public virtual DbSet<Seguro_doencas> Seguro_doencas { get; set; }
        public virtual DbSet<Seguro_empresa> Seguro_empresa { get; set; }
        public virtual DbSet<Seguro_empresa_usuario> Seguro_empresa_usuario { get; set; }
        public virtual DbSet<Seguro_empresa_usuario_depedente> Seguro_empresa_usuario_depedente { get; set; }
        public virtual DbSet<Seguro_empresa_usuario_doencas> Seguro_empresa_usuario_doencas { get; set; }
        public virtual DbSet<Seguro_empresa_usuario_farmacia> Seguro_empresa_usuario_farmacia { get; set; }
        public virtual DbSet<Seguro_empresa_usuario_medicamento> Seguro_empresa_usuario_medicamento { get; set; }
        public virtual DbSet<Seguro_tipo> Seguro_tipo { get; set; }
        public virtual DbSet<Seguro_usuario> Seguro_usuario { get; set; }
        public virtual DbSet<Seguro_usuario_farmacia> Seguro_usuario_farmacia { get; set; }
        public virtual DbSet<Seguro_usuario_medicamento> Seguro_usuario_medicamento { get; set; }
        public virtual DbSet<Sucursal_farmacia> Sucursal_farmacia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_logado> Usuario_logado { get; set; }

        public System.Data.Entity.DbSet<afarmaciaApi.Models.Autorizacao> Autorizacaos { get; set; }

        public System.Data.Entity.DbSet<afarmaciaApi.Models.Resumo_pesquisa> Resumocs { get; set; }

        public System.Data.Entity.DbSet<afarmaciaApi.Models.Pesquisas> Pesquisas { get; set; }
    }
}
