//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public long id_medicamento { get; set; }
        public long id_farmacia { get; set; }
        public long id_fabricante { get; set; }
        public int referencia { get; set; }
        public long id_usuario { get; set; }
        public string id_registo { get; set; }
        public Nullable<int> quantidade { get; set; }
        public string desc_quantidade { get; set; }
        public Nullable<decimal> valor_quantidade { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public string prescricao { get; set; }
        public string observacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situcao { get; set; }
    
        public virtual Medicamento_farmacia Medicamento_farmacia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
