//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public long id_comentario { get; set; }
        public string nome { get; set; }
        public string tipo_comentario { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public System.DateTime data_publicacao { get; set; }
        public string comentario1 { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public int estado { get; set; }
        public int situacao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
