//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dependente()
        {
            this.Seguro_depedente = new HashSet<Seguro_depedente>();
            this.Seguro_empresa_usuario_depedente = new HashSet<Seguro_empresa_usuario_depedente>();
        }
    
        public long id_dependente { get; set; }
        public string nome { get; set; }
        public string apelido { get; set; }
        public string telefone { get; set; }
        public string grau_parentesco { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public Nullable<int> acesso { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public string prioridade { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_depedente> Seguro_depedente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_depedente> Seguro_empresa_usuario_depedente { get; set; }
    }
}
