//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doencas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doencas()
        {
            this.Seguro_doencas = new HashSet<Seguro_doencas>();
            this.Seguro_empresa_usuario_doencas = new HashSet<Seguro_empresa_usuario_doencas>();
        }
    
        public long id_doenca { get; set; }
        public string designacao { get; set; }
        public string manifestacao { get; set; }
        public string descricao { get; set; }
        public string tratamento { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_doencas> Seguro_doencas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_doencas> Seguro_empresa_usuario_doencas { get; set; }
    }
}
