//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public long id_log { get; set; }
        public Nullable<long> id_logado { get; set; }
        public string pagina { get; set; }
        public Nullable<System.DateTime> visita { get; set; }
        public Nullable<System.DateTime> saida { get; set; }
        public string tipo_acao { get; set; }
        public Nullable<int> estado_acao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        public virtual Usuario_logado Usuario_logado { get; set; }
    }
}
