//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamento()
        {
            this.Medicamento_farmacia = new HashSet<Medicamento_farmacia>();
            this.Receita = new HashSet<Receita>();
            this.Seguro_empresa_usuario_medicamento = new HashSet<Seguro_empresa_usuario_medicamento>();
            this.Seguro_usuario_medicamento = new HashSet<Seguro_usuario_medicamento>();
        }
    
        public long id_medicamento { get; set; }
        public string nome { get; set; }
        public string marca { get; set; }
        public string descricao { get; set; }
        public string composicao { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> autorizacao { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<long> id_grupo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        public virtual Grupo_medicamento Grupo_medicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento_farmacia> Medicamento_farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receita> Receita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_medicamento> Seguro_empresa_usuario_medicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_usuario_medicamento> Seguro_usuario_medicamento { get; set; }
    }
}
