//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordem()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public string ordem1 { get; set; }
        public Nullable<long> id_farmacia { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<int> medicamentos { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public string observacao { get; set; }
        public string observacao_emissao { get; set; }
        public string observacao_cancelamento { get; set; }
    
        public virtual Sucursal_farmacia Sucursal_farmacia { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
