//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicao_padrao
    {
        public long id_coordenadas { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
