//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provincia()
        {
            this.Distrito = new HashSet<Distrito>();
        }
    
        public int id_provincia { get; set; }
        public string designacao { get; set; }
        public string descricao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public int id_regiao { get; set; }
        public string id_mapa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distrito> Distrito { get; set; }
        public virtual Regiao Regiao { get; set; }
    }
}
