//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita
    {
        public long id_registo { get; set; }
        public long id_medicamento { get; set; }
        public long id_usuario { get; set; }
        public string data { get; set; }
        public Nullable<int> quantidade { get; set; }
        public string composicao { get; set; }
        public string forma { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
