//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        public long id { get; set; }
        public string designacao { get; set; }
        public string descricao { get; set; }
        public string nome { get; set; }
        public string nome2 { get; set; }
        public string nome3 { get; set; }
        public string nome4 { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<long> total_registo { get; set; }
        public Nullable<decimal> total_valor { get; set; }
        public Nullable<decimal> valor_inicial { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<int> situacao1 { get; set; }
        public Nullable<int> estado1 { get; set; }
    }
}
