//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguro_empresa()
        {
            this.Seguro_empresa_usuario = new HashSet<Seguro_empresa_usuario>();
        }
    
        public long id_seguradora { get; set; }
        public int id_categoria { get; set; }
        public long id_empresa { get; set; }
        public int id_tipo { get; set; }
        public Nullable<int> numero_segurado { get; set; }
        public string cobertura { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> abertura { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Seguradora Seguradora { get; set; }
        public virtual Seguro_categoria Seguro_categoria { get; set; }
        public virtual Seguro_tipo Seguro_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario> Seguro_empresa_usuario { get; set; }
    }
}
