//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro_tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguro_tipo()
        {
            this.Seguro_empresa = new HashSet<Seguro_empresa>();
            this.Seguro_usuario = new HashSet<Seguro_usuario>();
        }
    
        public int id_tipo { get; set; }
        public string designacao { get; set; }
        public string descricao { get; set; }
        public string aplicacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa> Seguro_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_usuario> Seguro_usuario { get; set; }
    }
}
