//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro_empresa_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguro_empresa_usuario()
        {
            this.Seguro_empresa_usuario_depedente = new HashSet<Seguro_empresa_usuario_depedente>();
            this.Seguro_empresa_usuario_doencas = new HashSet<Seguro_empresa_usuario_doencas>();
            this.Seguro_empresa_usuario_farmacia = new HashSet<Seguro_empresa_usuario_farmacia>();
            this.Seguro_empresa_usuario_medicamento = new HashSet<Seguro_empresa_usuario_medicamento>();
        }
    
        public long id_seguradora { get; set; }
        public int id_categoria { get; set; }
        public long id_empresa { get; set; }
        public int id_tipo { get; set; }
        public long id_usuario { get; set; }
        public Nullable<int> numero_segurado { get; set; }
        public string cobertura { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> abertura { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        public virtual Seguro_empresa Seguro_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_depedente> Seguro_empresa_usuario_depedente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_doencas> Seguro_empresa_usuario_doencas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_farmacia> Seguro_empresa_usuario_farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_medicamento> Seguro_empresa_usuario_medicamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
