//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguradora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguradora()
        {
            this.Seguro_empresa = new HashSet<Seguro_empresa>();
            this.Seguro_usuario = new HashSet<Seguro_usuario>();
        }
    
        public long id_segurador { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string nuit { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string area_actuacao { get; set; }
        public string web_site { get; set; }
        public string localzacao { get; set; }
        public string logotipo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<long> id_avenida { get; set; }
    
        public virtual Avenida Avenida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa> Seguro_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_usuario> Seguro_usuario { get; set; }
    }
}
