//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal_farmacia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal_farmacia()
        {
            this.Classificacao_farmacia = new HashSet<Classificacao_farmacia>();
            this.Medicamento_farmacia = new HashSet<Medicamento_farmacia>();
            this.Ordem = new HashSet<Ordem>();
            this.Seguro_empresa_usuario_farmacia = new HashSet<Seguro_empresa_usuario_farmacia>();
            this.Seguro_usuario_farmacia = new HashSet<Seguro_usuario_farmacia>();
        }
    
        public long id_sucursal { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string alvara { get; set; }
        public Nullable<System.DateTime> data_alvara { get; set; }
        public string localizacao { get; set; }
        public string logo { get; set; }
        public string lema { get; set; }
        public string horario { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public string link_localizacao { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<long> id_distrito { get; set; }
        public Nullable<long> id_farmacia { get; set; }
        public Nullable<long> id_avenida { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string web_site { get; set; }
        public string fax { get; set; }
    
        public virtual Avenida Avenida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classificacao_farmacia> Classificacao_farmacia { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Farmacia Farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento_farmacia> Medicamento_farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordem> Ordem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario_farmacia> Seguro_empresa_usuario_farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_usuario_farmacia> Seguro_usuario_farmacia { get; set; }
    }
}
