//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_logado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario_logado()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public long id_logado { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<System.DateTime> entrada { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public Nullable<System.DateTime> saida { get; set; }
        public string dispositivo { get; set; }
        public string browser { get; set; }
        public string versao_browser { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
