//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afarmaciaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Assinante = new HashSet<Assinante>();
            this.Carrinho = new HashSet<Carrinho>();
            this.Classificacao_farmacia = new HashSet<Classificacao_farmacia>();
            this.Comentario = new HashSet<Comentario>();
            this.Dependente = new HashSet<Dependente>();
            this.Ordem = new HashSet<Ordem>();
            this.Posicao_padrao = new HashSet<Posicao_padrao>();
            this.Receita = new HashSet<Receita>();
            this.Seguro_empresa_usuario = new HashSet<Seguro_empresa_usuario>();
            this.Seguro_usuario = new HashSet<Seguro_usuario>();
            this.Usuario_logado = new HashSet<Usuario_logado>();
        }
    
        public long id_usuario { get; set; }
        public string nome { get; set; }
        public string apelido { get; set; }
        public string tipo { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string origem { get; set; }
        public string usuario1 { get; set; }
        public string senha { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> registo { get; set; }
        public Nullable<System.DateTime> actualizacao { get; set; }
        public string recover { get; set; }
        public string link_registo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assinante> Assinante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Categoria_usuario Categoria_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classificacao_farmacia> Classificacao_farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dependente> Dependente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordem> Ordem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posicao_padrao> Posicao_padrao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receita> Receita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_empresa_usuario> Seguro_empresa_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro_usuario> Seguro_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_logado> Usuario_logado { get; set; }
    }
}
